### ISSUE TITLE
Raise indicative error in case client used unknown type

### ISSUE THREAD

**Issue by doriaviram** [doriaviram/super-yaml#14]
Example of use case:
```yaml
TestStudent<Student>: 
   name: "SuperName"
DummyStudent:
   name: DummyStudent
```
While `Student` type is not defined and not required
