### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by Kashio** [doriaviram/super-yaml#17]
```
types:
  HTTPStatus:
    template:
      name: $nameParam
      class: Math
	  description: Lambda of $nameParam
  Response:
	properties:
		status:
			type: $HTTPStatus
		data:
			type: string

TestStudent1<Student>:
  name: xxxx
  description: Lambda of $name
TestStudent2<Student>:
  nameParam: SuperName2
DummyStudent:
  name: "DummyStudent"
  
  
 TestStudent1:
  name: "SuperName1"
  class: "Math"
  description: Lambda of SuperName1
TestStudent2:
  name: "SuperName2"
  class: "Math"
DummyStudent:
  name: "DummyStudent"
  
  
_types:
  Student:
    properties:
      name:
		type: string
		default: my-api
	  description:
		type: string
		default: Lambda of $name
		
@core/import

type: @http-types-by-roymor/HTTPStatus
```
